language: python

python:
  - 2.7
  - 3.4

install:
  - pip install pybuilder
  - pyb install_dependencies --verbose
  - pip install python-coveralls

script:
  - pyb --verbose

after_success:
  - coveralls
